# Notebook 1 : Découverte de Pandas

In [1]:
import pandas as pd

## Iris

Nous considérons le jeu de données connu sous le nom des [Iris de Fisher](https://fr.wikipedia.org/wiki/Iris_de_Fisher). Répondez aux questions suivantes à l'aide du module Pandas.

1. Charger le jeu de données dans un dataframe `iris` à partir du fichier `iris.csv` et afficher le dataframe.

In [ ]:
iris = pd.read_csv("~/work/DATA/iris.csv", sep=',')
iris.head

   SepalLength  SepalWidth  PetalLength  PetalWidth Species
0          5.1         3.5          1.4         0.2  setosa
1          4.9         3.0          1.4         0.2  setosa
2          4.7         3.2          1.3         0.2  setosa
3          4.6         3.1          1.5         0.2  setosa
4          5.0         3.6          1.4         0.2  setosa

2. Sélectionner les variables `PetalWidth` et `Species`.

In [16]:
iris.filter(["PetalWidth","Species"])

     PetalWidth    Species
0           0.2     setosa
1           0.2     setosa
2           0.2     setosa
3           0.2     setosa
4           0.2     setosa
..          ...        ...
145         2.3  virginica
146         1.9  virginica
147         2.0  virginica
148         2.3  virginica
149         1.8  virginica

[150 rows x 2 columns]

3. Extraire le sous-dataframe qui contient uniquement les iris des espèces `versicolor` ou `virginica`.

In [17]:
iris[iris["Species"].isin(["versicolor", "virginica"])]

     SepalLength  SepalWidth  PetalLength  PetalWidth     Species
50           7.0         3.2          4.7         1.4  versicolor
51           6.4         3.2          4.5         1.5  versicolor
52           6.9         3.1          4.9         1.5  versicolor
53           5.5         2.3          4.0         1.3  versicolor
54           6.5         2.8          4.6         1.5  versicolor
..           ...         ...          ...         ...         ...
145          6.7         3.0          5.2         2.3   virginica
146          6.3         2.5          5.0         1.9   virginica
147          6.5         3.0          5.2         2.0   virginica
148          6.2         3.4          5.4         2.3   virginica
149          5.9         3.0          5.1         1.8   virginica

[100 rows x 5 columns]

4. Compter le nombre d'iris de l'espèce `setosa`.

In [18]:
iris[iris["Species"]=="setosa"].count()

SepalLength    50
SepalWidth     50
PetalLength    50
PetalWidth     50
Species        50
dtype: int64

5. Calculer la moyenne de la variable `PetalWidth` pour les iris de l'espèce `versicolor`.

In [19]:
iris[iris["Species"]=="versicolor"]["PetalWidth"].mean()

np.float64(1.3259999999999998)

6. Ajouter une variable `SumWidth` qui contient la somme des variables `PetalWidth` et `SepalWidth`.

In [20]:
iris["SumWidth"] = iris["PetalWidth"] + iris["SepalWidth"]
iris.head()

   SepalLength  SepalWidth  PetalLength  PetalWidth Species  SumWidth
0          5.1         3.5          1.4         0.2  setosa       3.7
1          4.9         3.0          1.4         0.2  setosa       3.2
2          4.7         3.2          1.3         0.2  setosa       3.4
3          4.6         3.1          1.5         0.2  setosa       3.3
4          5.0         3.6          1.4         0.2  setosa       3.8

7. Calculer la moyenne et la variance de la variable `SepalLength` pour chaque espèce.

In [22]:
iris.groupby("Species")["SepalLength"].agg("mean")

Species
setosa        5.006
versicolor    5.936
virginica     6.588
Name: SepalLength, dtype: float64

8. Calculer la moyenne de toutes les variables pour chaque espèce. Afficher le résultat au format large et au format long.

In [27]:
iris_agg_large = iris.groupby("Species").mean(numeric_only=True)
iris_agg_long = iris_agg_large.reset_index().melt(
    id_vars="Species",
    var_name="Variable",
    value_name="Moyenne"
)

In [28]:
iris_agg_large

            SepalLength  SepalWidth  PetalLength  PetalWidth  SumWidth
Species
setosa            5.006       3.428        1.462       0.246     3.674
versicolor        5.936       2.770        4.260       1.326     4.096
virginica         6.588       2.974        5.552       2.026     5.000

In [29]:
iris_agg_long

       Species     Variable  Moyenne
0       setosa  SepalLength    5.006
1   versicolor  SepalLength    5.936
2    virginica  SepalLength    6.588
3       setosa   SepalWidth    3.428
4   versicolor   SepalWidth    2.770
5    virginica   SepalWidth    2.974
6       setosa  PetalLength    1.462
7   versicolor  PetalLength    4.260
8    virginica  PetalLength    5.552
9       setosa   PetalWidth    0.246
10  versicolor   PetalWidth    1.326
11   virginica   PetalWidth    2.026
12      setosa     SumWidth    3.674
13  versicolor     SumWidth    4.096
14   virginica     SumWidth    5.000

## Houston flights

Nous considérons le jeux de données `hflights` relatif à des vols au départ des aéroports *Houston George Bush Intercontinental Airport* (IAH) et *William P. Hobby Airport* (HOU).

1. Charger le jeu de données dans un dataframe `hflights` à partir du fichier `hflights.csv`

In [31]:
hflights = pd.read_csv("~/work/DATA/hflights.csv", sep=',')
hflights.head()

,Year,Month,DayofMonth,DayOfWeek,DepTime,ArrTime,UniqueCarrier,FlightNum,TailNum,ActualElapsedTime,...,ArrDelay,DepDelay,Origin,Dest,Distance,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted
0,2011,1,1,6,1400.0,1500.0,AA,428,N576AA,60.0,...,-10.0,0.0,IAH,DFW,224,7.0,13.0,0,NaN,0
1,2011,1,2,7,1401.0,1501.0,AA,428,N557AA,60.0,...,-9.0,1.0,IAH,DFW,224,6.0,9.0,0,NaN,0
2,2011,1,3,1,1352.0,1502.0,AA,428,N541AA,70.0,...,-8.0,-8.0,IAH,DFW,224,5.0,17.0,0,NaN,0
3,2011,1,4,2,1403.0,1513.0,AA,428,N403AA,70.0,...,3.0,3.0,IAH,DFW,224,9.0,22.0,0,NaN,0
4,2011,1,5,3,1405.0,1507.0,AA,428,N492AA,62.0,...,-3.0,5.0,IAH,DFW,224,9.0,9.0,0,NaN,0

2. Sélectionner les variable `Dest`, `Distance`, `TaxiIn` et `TaxiOut` avec la méthode `filter`.

In [32]:
hflights_select = hflights.filter(items=["Dest", "Distance", "TaxiIn", "TaxiOut"])
hflights_select.head()

  Dest  Distance  TaxiIn  TaxiOut
0  DFW       224     7.0     13.0
1  DFW       224     6.0      9.0
2  DFW       224     5.0     17.0
3  DFW       224     9.0     22.0
4  DFW       224     9.0      9.0

3. Sélectionner les variables `DepTime`, `ArrTime`, `ActualElapsedTime` et `AirTime` avec la méthode `filter` et le paramètre `like`.

In [33]:
hflights_select_like = hflights.filter(like="Time")
hflights_select_like.head()

   DepTime  ArrTime  ActualElapsedTime  AirTime
0   1400.0   1500.0               60.0     40.0
1   1401.0   1501.0               60.0     45.0
2   1352.0   1502.0               70.0     48.0
3   1403.0   1513.0               70.0     39.0
4   1405.0   1507.0               62.0     44.0

4. Ajouter une variable `ActualGroundTime` qui correspond à `ActualElapsedTime` moins `AirTime`.

In [35]:
hflights["ActualGroundTime"] = hflights["ActualElapsedTime"] - hflights["AirTime"]
hflights.head()

,Year,Month,DayofMonth,DayOfWeek,DepTime,ArrTime,UniqueCarrier,FlightNum,TailNum,ActualElapsedTime,...,DepDelay,Origin,Dest,Distance,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,ActualGroundTime
0,2011,1,1,6,1400.0,1500.0,AA,428,N576AA,60.0,...,0.0,IAH,DFW,224,7.0,13.0,0,NaN,0,20.0
1,2011,1,2,7,1401.0,1501.0,AA,428,N557AA,60.0,...,1.0,IAH,DFW,224,6.0,9.0,0,NaN,0,15.0
2,2011,1,3,1,1352.0,1502.0,AA,428,N541AA,70.0,...,-8.0,IAH,DFW,224,5.0,17.0,0,NaN,0,22.0
3,2011,1,4,2,1403.0,1513.0,AA,428,N403AA,70.0,...,3.0,IAH,DFW,224,9.0,22.0,0,NaN,0,31.0
4,2011,1,5,3,1405.0,1507.0,AA,428,N492AA,62.0,...,5.0,IAH,DFW,224,9.0,9.0,0,NaN,0,18.0

5. Ajouter une variable `AverageSpeed` qui donne la vitesse moyenne du vol et ordonner la table selon les valeurs décroissantes de cette variable.

In [37]:
hflights = hflights.assign(
    AverageSpeed=hflights["Distance"] / (hflights["AirTime"] / 60)
).sort_values(by="AverageSpeed", ascending=False)
hflights.head()

,Year,Month,DayofMonth,DayOfWeek,DepTime,ArrTime,UniqueCarrier,FlightNum,TailNum,ActualElapsedTime,...,Origin,Dest,Distance,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,ActualGroundTime,AverageSpeed
147589,2011,8,31,3,1255.0,1346.0,CO,1646,N11612,51.0,...,IAH,AUS,140,8.0,32.0,0,NaN,0,40.0,763.636364
8318,2011,1,8,6,1620.0,1730.0,EV,5229,N451CA,70.0,...,IAH,MEM,469,10.0,18.0,0,NaN,0,28.0,670.000000
34761,2011,2,21,1,834.0,1156.0,US,944,N409US,142.0,...,IAH,CLT,913,22.0,35.0,0,NaN,0,57.0,644.470588
185953,2011,10,9,7,1104.0,1117.0,XE,4634,N11121,73.0,...,IAH,HOB,501,13.0,13.0,0,NaN,0,26.0,639.574468
40764,2011,3,9,3,1905.0,2225.0,CO,500,N19638,140.0,...,IAH,IND,845,6.0,52.0,0,NaN,0,58.0,618.292683

6. Sélectionner les vols à destination de `JFK`.

In [ ]:
hflights_JFK = hflights[hflights["Dest"] == "JFK"]
hflights_JFK.head()

,Year,Month,DayofMonth,DayOfWeek,DepTime,ArrTime,UniqueCarrier,FlightNum,TailNum,ActualElapsedTime,...,Origin,Dest,Distance,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,ActualGroundTime,AverageSpeed
19193,2011,2,7,1,659.0,1045.0,B6,620,N607JB,166.0,...,HOU,JFK,1428,5.0,14.0,0,NaN,0,19.0,582.857143
19191,2011,2,6,7,700.0,1045.0,B6,620,N657JB,165.0,...,HOU,JFK,1428,4.0,10.0,0,NaN,0,14.0,567.417219
19190,2011,2,5,6,700.0,1113.0,B6,620,N653JB,193.0,...,HOU,JFK,1428,8.0,32.0,0,NaN,0,40.0,560.000000
19192,2011,2,6,7,1529.0,1917.0,B6,624,N531JB,168.0,...,HOU,JFK,1428,5.0,9.0,0,NaN,0,14.0,556.363636
19201,2011,2,12,6,659.0,1105.0,B6,620,N612JB,186.0,...,HOU,JFK,1428,6.0,24.0,0,NaN,0,30.0,549.230769

7. Compter le nombre de vols à destination de `JFK`.

In [48]:
print(hflights_JFK.count())
print(len(hflights_JFK))

Year                 695
Month                695
DayofMonth           695
DayOfWeek            695
DepTime              677
ArrTime              677
UniqueCarrier        695
FlightNum            695
TailNum              695
ActualElapsedTime    673
AirTime              673
ArrDelay             673
DepDelay             677
Origin               695
Dest                 695
Distance             695
TaxiIn               677
TaxiOut              677
Cancelled            695
CancellationCode      18
Diverted             695
ActualGroundTime     673
AverageSpeed         673
dtype: int64
695

8. Agréger les données `hflights` pour obtenir :
- `n` : le nombre total de vols,
- `n_dest`: le nombre total de destinations distinctes,
- `n_carrier` : le nombre total de compagnies distinctes.

In [ ]:
result = hflights.agg(
    n=('FlightNum', 'count'),         
    n_dest=('Dest', 'nunique'),       
    n_carrier=('UniqueCarrier', 'nunique')  
)

print(result)

           FlightNum   Dest  UniqueCarrier
n           227496.0    NaN            NaN
n_dest           NaN  116.0            NaN
n_carrier        NaN    NaN           15.0

9. Agréger les données des vols de la compagnie `AA` pour obtenir :
- le nombre total de vols,
- le nombre total de vols annulés,
- la valeur moyenne de `ArrDelay`.

10. Calculer pour chaque compagnie :
- le nombre total de vols,
- la valeur moyenne de `AirTime`.

11. Ordonner les compagnies en fonction des retards moyens au départ.